modLoader="javafml" 
loaderVersion="[28,)" 
#issueTrackerURL=""

[[mods]] 
modId="mightyarchitect"
version="0.4.5"
displayName="The Mighty Architect" 
#updateJSONURL=""
authors="simibubi" 
description='''Design elaborate buildings within a minute! [G] is the default keybind for getting started. Check out the wiki for more info.'''

[[dependencies.mightyarchitect]] 
    modId="forge"
    mandatory=true 
    versionRange="[28.0.45,)"
    ordering="NONE"
    side="CLIENT"
	
[[dependencies.mightyarchitect]] 
    modId="forge"
    mandatory=true 
    versionRange="[28,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.mightyarchitect]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"